options:
  logging: "CLOUD_LOGGING_ONLY"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/home-page:latest", "."]

# Push is handled by listing the image under `images` — Cloud Build will push it for us.
images:
  - "gcr.io/$PROJECT_ID/home-page:latest"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - home-page
      - --image
      - gcr.io/$PROJECT_ID/home-page:latest
      - --region
      - $_REGION
      - --platform
      - managed
      - --allow-unauthenticated

